# Generated by Django 3.1.7 on 2021-03-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=14)),
                ('estado_Civil', models.CharField(max_length=25)),
                ('contato_SMS', models.CharField(max_length=11)),
                ('whatsapp', models.CharField(max_length=20)),
            ],
        ),
    ]
