# Generated by Django 3.2 on 2021-05-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Agencia', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=20)),
                ('nome_Dono', models.CharField(max_length=40)),
                ('logradouro', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=20)),
                ('nome_Rua', models.CharField(max_length=40)),
                ('numero_Rua', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('doc_Contrato_Social', models.CharField(max_length=200)),
                ('doc_Historia_Empresa', models.CharField(max_length=200)),
                ('qtde_Func', models.IntegerField()),
                ('qtde_Dep', models.IntegerField()),
                ('qtde_Anunciantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=14)),
                ('estado_Civil', models.CharField(max_length=25)),
                ('contato_SMS', models.CharField(max_length=11)),
                ('whatsapp', models.CharField(max_length=11)),
                ('senha_Cliente', models.CharField(max_length=15)),
                ('nome_De_Usuario', models.CharField(max_length=40)),
                ('email_Cliente', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco_Empresa_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Rua_Comercial', models.CharField(max_length=40)),
                ('num_Rua_Comercial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidade_Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_Pag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_Cliente', models.IntegerField()),
                ('id_Cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Logradouro', models.CharField(max_length=15)),
                ('id_Estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.localidade_estado')),
            ],
        ),
        migrations.CreateModel(
            name='Telefones_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Telefone', models.CharField(max_length=11)),
                ('id_Cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Tipo_Telefone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema_Rn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Agencia', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.agencia')),
                ('id_Cliente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Resultado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Localidade_Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Cidade', models.CharField(max_length=20)),
                ('id_Estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.localidade_estado')),
            ],
        ),
        migrations.CreateModel(
            name='Localidade_Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Bairro', models.CharField(max_length=20)),
                ('id_Localidade_Cidade', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.localidade_cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balancos', models.CharField(max_length=200)),
                ('faturamento_Anual', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('doc_Contrato_Social', models.CharField(max_length=120)),
                ('renda_Bruta_Anual', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('indice_Liquidez', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('doc_Indice_Dividas', models.CharField(max_length=60)),
                ('rentabilidade_Investimentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('holerites_Doc', models.CharField(max_length=60)),
                ('doc_Declaracao_IR', models.CharField(max_length=60)),
                ('receita_Operacional', models.DateField()),
                ('doc_Valores_Contabeis', models.CharField(max_length=40)),
                ('id_Cliente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Endereco_Empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.endereco_empresa_cliente')),
            ],
        ),
        migrations.AddField(
            model_name='endereco_empresa_cliente',
            name='id_Tipo_Logradouro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_logradouro'),
        ),
        migrations.CreateModel(
            name='Endereco_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Rua', models.CharField(max_length=40)),
                ('num_Rua', models.IntegerField()),
                ('complemento', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('id_Cliente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Tipo_Logradouro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_logradouro')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('data_Solicitacao', models.DateField()),
                ('qtde_Parcelas', models.IntegerField()),
                ('valor_unitario', models.IntegerField()),
                ('id_Cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Pagamento', models.DateField()),
                ('id_Cliente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Pag', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Adm', models.CharField(max_length=20)),
                ('senha_Adm', models.CharField(max_length=15)),
                ('id_Agencia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.agencia')),
                ('id_Cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
