# Generated by Django 3.2 on 2021-05-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='situacao',
            field=models.CharField(default=-1, max_length=40),
            preserve_default=False,
        ),
    ]
