# Generated by Django 3.2 on 2021-05-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_emprestimo_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='id_Cliente',
        ),
    ]
