# Generated by Django 3.2 on 2021-06-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_emprestimo_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id_Cliente',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='id_Endereco_Empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.endereco_empresa_cliente'),
        ),
    ]
