# Generated by Django 3.2 on 2021-06-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210601_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='receita_Operacional',
            field=models.CharField(max_length=200),
        ),
    ]
