# Generated by Django 3.2 on 2021-06-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210601_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
    ]
