# Generated by Django 3.1.7 on 2021-03-27 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Pagamento', models.DateField()),
                ('id_Cliente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Pag', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.pagamento')),
            ],
        ),
    ]
