# Generated by Django 3.1.7 on 2021-03-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cliente_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade_Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Estado', models.CharField(max_length=20)),
            ],
        ),
    ]
