# Generated by Django 3.2 on 2021-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pagamento_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_unitario',
            field=models.IntegerField(null=True),
        ),
    ]
