# Generated by Django 3.2 on 2021-06-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_emprestimo_valor_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='id_Cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
