# Generated by Django 3.2 on 2021-06-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_emprestimo_valor_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='nomeCliente',
            field=models.CharField(default=1.0, max_length=40),
            preserve_default=False,
        ),
    ]
