# Generated by Django 3.1.7 on 2021-03-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_localidade_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Logradouro', models.CharField(max_length=15)),
                ('id_Estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.localidade_estado')),
            ],
        ),
    ]
