# Generated by Django 3.1.7 on 2021-03-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tipo_logradouro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco_Empresa_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Rua_Comercial', models.CharField(max_length=40)),
                ('num_Rua_Comercial', models.IntegerField()),
                ('id_Tipo_Logradouro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_logradouro')),
            ],
        ),
    ]
