# Generated by Django 3.2 on 2021-06-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_formulario_nomecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='inadimplentes',
            field=models.IntegerField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='pag_atrasados',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='pag_em_dia',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='total_clientes',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='envioDocs',
            field=models.IntegerField(default=1.0),
            preserve_default=False,
        ),
    ]
