# Generated by Django 3.1.7 on 2021-03-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_endereco_empresa_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balancos', models.CharField(max_length=200)),
                ('faturamento_Anual', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('doc_Contrato_Social', models.CharField(max_length=120)),
                ('renda_Bruta_Anual', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('indice_Liquidez', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('doc_Indice_Dividas', models.CharField(max_length=100)),
                ('rentabilidade_Investimentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('holerites_Doc', models.CharField(max_length=100)),
                ('doc_Declaracao_IR', models.CharField(max_length=100)),
                ('receita_Operacional', models.DateField()),
                ('doc_Valores_Contabeis', models.CharField(max_length=40)),
                ('id_Cliente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Endereco_Empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.endereco_empresa_cliente')),
            ],
        ),
    ]
