# Generated by Django 3.1.7 on 2021-03-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
