# Generated by Django 3.2 on 2021-06-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_resultado_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='inadimplencia',
            field=models.IntegerField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='nomeCliente',
            field=models.CharField(default=-1.0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='pagamento_em_dia',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
    ]
