# Generated by Django 3.1.7 on 2021-03-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tipo_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefones_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Telefone', models.CharField(max_length=11)),
                ('id_Cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Tipo_Telefone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_telefone')),
            ],
        ),
    ]
