# Generated by Django 3.1.7 on 2021-03-27 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_telefones_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Rua', models.CharField(max_length=40)),
                ('num_Rua', models.IntegerField()),
                ('complemento', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('id_Cliente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_Tipo_Logradouro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_logradouro')),
            ],
        ),
    ]
