# Generated by Django 3.1.7 on 2021-03-27 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_endereco_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_Cadastral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_Cliente', models.CharField(max_length=15)),
                ('nome_De_Usuario', models.CharField(max_length=40)),
                ('email_Cliente', models.EmailField(max_length=254)),
                ('id_Cliente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
