# Generated by Django 3.1.7 on 2021-03-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ficha_cadastral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Agencia', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=20)),
                ('nome_Dono', models.CharField(max_length=40)),
                ('logradouro', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=20)),
                ('nome_Rua', models.CharField(max_length=40)),
                ('numero_Rua', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('doc_Contrato_Social', models.CharField(max_length=200)),
                ('doc_Historia_Empresa', models.CharField(max_length=200)),
                ('qtde_Func', models.IntegerField()),
                ('qtde_Dep', models.IntegerField()),
                ('qtde_Anunciantes', models.IntegerField()),
            ],
        ),
    ]
