# Generated by Django 3.1.7 on 2021-03-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Adm', models.CharField(max_length=20)),
                ('id_Agencia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.agencia')),
                ('id_Cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
