# Generated by Django 3.1.7 on 2021-03-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema_Rn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Agencia', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.agencia')),
                ('id_Ficha_Cadastral', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.ficha_cadastral')),
                ('id_Resultado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.resultado')),
            ],
        ),
    ]
