# Generated by Django 3.1.7 on 2021-03-27 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_sistema_rn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade_Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Cidade', models.CharField(max_length=20)),
                ('id_Estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.localidade_estado')),
            ],
        ),
    ]
