# Generated by Django 3.1.7 on 2021-04-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_localidade_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='doc_Declaracao_IR',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='doc_Indice_Dividas',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='holerites_Doc',
            field=models.CharField(max_length=60),
        ),
    ]
