# Generated by Django 3.1.7 on 2021-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210401_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_cadastral',
            name='senha_Cliente',
            field=models.IntegerField(),
        ),
    ]
