# Generated by Django 3.2 on 2021-04-30 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210415_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema_rn',
            name='id_Ficha_Cadastral',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_Cliente',
            field=models.EmailField(default=-1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_De_Usuario',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_Cliente',
            field=models.CharField(default=-1.0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sistema_rn',
            name='id_Cliente',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.DeleteModel(
            name='Ficha_Cadastral',
        ),
    ]
