# Generated by Django 3.2 on 2021-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210430_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='senha_Adm',
            field=models.CharField(default=-1.0, max_length=15),
            preserve_default=False,
        ),
    ]
