# Generated by Django 3.2 on 2021-05-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_administrador_senha_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_Agencia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.agencia'),
        ),
    ]
