# Generated by Django 3.2 on 2021-05-05 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_administrador_id_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_Cliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
