# Generated by Django 3.2 on 2021-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_emprestimo_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo_valor',
            name='qtde_Parcelas',
            field=models.CharField(max_length=2),
        ),
    ]
