# Generated by Django 3.2 on 2021-05-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_emprestimo_valor_qtde_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='id_Cliente',
            field=models.ForeignKey(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
