# Generated by Django 3.2 on 2021-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210512_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo_valor',
            name='qtde_Parcelas',
            field=models.IntegerField(max_length=2),
        ),
    ]
