# Generated by Django 3.2 on 2021-05-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_emprestimo_valor_qtde_parcelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='id_Cliente',
        ),
    ]
