# Generated by Django 3.2 on 2021-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_emprestimo_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_pagamento',
            name='data_Pagamento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
