# Generated by Django 3.2 on 2021-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_cliente_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_pagamento',
            name='data_Pagamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_Solicitacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
