# Generated by Django 3.2 on 2021-05-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210512_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_Solicitacao',
        ),
    ]
