# Generated by Django 3.2 on 2021-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_emprestimo_data_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_Solicitacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
