# Generated by Django 3.2 on 2021-05-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_emprestimo_data_solicitacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprestimo_Valor',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='qtde_Parcelas',
            field=models.IntegerField(default=-1.0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='situacao',
            field=models.CharField(default=-1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=60, default=0.0, max_digits=60),
        ),
    ]
